function [post_mean, post_var]...
    = lap_diag(logf_inter, logf_at_mode, Us, s_star, logdet_T, d,...
    gam, lambda, alph, lap_app)

Y = exp(d*log(gam)+logdet_T)*...
    (exp(logf_inter -log(mvnpdf(s_star/gam)))-...
    (2*pi)^d*exp(logf_at_mode + log(mvnpdf(sqrt(gam^2-1)*s_star/gam))));

k = @(r)exp(-r.^2/(2*lambda^2));
kmean = @(x)(lambda^2/(gam^2+lambda^2))^(d/2)*...
    exp(-norm(x)^2/(2*(gam^2+lambda^2)));
Ikmean = (lambda^2/(2*gam^2 + lambda^2))^(d/2);

[Q, wce, w] = kq_fss(Y, Us, k, kmean, Ikmean);
disp(w)
post_mean = Q + lap_app;

post_var = wce^2*exp(2*(logf_at_mode + logdet_T) - d*log(alph));

lower_bound = min([norminv(0.025, post_mean, sqrt(post_var)) lap_app]);
upper_bound = max([norminv(0.975, post_mean, sqrt(post_var)) lap_app]);
lap_dist = fplot(@(x) normpdf(x, post_mean, sqrt(post_var)),...
    [lower_bound - 0.35*(upper_bound - lower_bound) upper_bound+...
    0.35*(upper_bound - lower_bound)], '-k','LineWidth', 1.5);
hold on
lap_line = xline(lap_app, '--b', 'LineWidth', 1.25);
quant_line = xline(norminv(0.025, post_mean, sqrt(post_var)), ':k',...
    'LineWidth', 1.35);
quant_line = xline(norminv(0.975, post_mean, sqrt(post_var)), ':k',...
    'LineWidth', 1.35);
legend([lap_dist, quant_line, lap_line],...
    {'Integral posterior', '95% interval',...
    'Laplace approximation'}, 'Location', 'southoutside');
hold off

